from dotenv import load_dotenv, find_dotenv
from starlette.config import Config

ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

config = Config(ENV_FILE)

HF_TOKEN = config("HF_TOKEN")
SYSTEM_PROMPT = config("SYSTEM_PROMPT")
AMADEUS_CLIENT_ID = config("AMADEUS_CLIENT_ID")
AMADEUS_SECRET_ID = config("AMADEUS_SECRET_ID")
OPENAI_API_KEY = config("OPENAI_API_KEY")
MAPBOX_API_KEY = config("MAPBOX_API_KEY")
OPENAI_ASSISTANT_ID = config("OPENAI_ASSISTANT_ID")
SOLARA_SESSION_SECRET_KEY = config("SOLARA_SESSION_SECRET_KEY")
SOLARA_OAUTH_CLIENT_ID = config("SOLARA_OAUTH_CLIENT_ID")
SOLARA_OAUTH_CLIENT_SECRET = config("SOLARA_OAUTH_CLIENT_SECRET")
SOLARA_OAUTH_API_BASE_URL = config("SOLARA_OAUTH_API_BASE_URL")
SOLARA_SESSION_HTTPS_ONLY = config("SOLARA_SESSION_HTTPS_ONLY")
SOLARA_OAUTH_SCOPE = config("SOLARA_OAUTH_SCOPE")